version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: eschool_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eschool_db
      MYSQL_USER: eschool_user
      MYSQL_PASSWORD: eschool_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - eschool_network

  ci4:
    build:
      context: ./ci4-api
      dockerfile: Dockerfile
    container_name: eschool_ci4
    ports:
      - "8080:80"
    volumes:
      - ./ci4-api:/var/www/html/public_html/eSchool
    environment:
      APP_ENVIRONMENT: development
      database.default.hostname: db
      database.default.database: eschool_db
      database.default.username: eschool_user
      database.default.password: eschool_password
      database.default.port: 3306
    depends_on:
      - db
    networks:
      - eschool_network

  angular:
    build:
      context: ./angular-app
      dockerfile: Dockerfile
    container_name: eschool_angular
    ports:
      - "4200:4200"
    volumes:
      - ./angular-app:/app
    depends_on:
      - ci4
    networks:
      - eschool_network

volumes:
  db_data:

networks:
  eschool_network:
    driver: bridge